Azure/kperf

api/types/metric.go, cmd/kperf/commands/runner/runner.go, metrics/request.go, metrics/request_test.go, metrics/utils.go, request/schedule.go, runner/utils.go
Introduce ResponseError type to record error client received. It includes timestamp, timespan in seconds and error message. The RunnerMetricReport will export raw data about each response error. It can help us build view about error.
```go
// ResponseError is the record about that error.
type ResponseError struct {
// Timestamp indicates when this error was received.
Timestamp time.Time `json:"timestamp"`
// Duration records timespan in seconds.
Duration float64 `json:"duration"`
// Type indicates that category to which the error belongs.
Type ResponseErrorType `json:"type"`
// Code only works when Type is http.
Code int `json:"code,omitempty"`
// Message shows error message for this error.
//
// NOTE: When Type is http, this field will be empty.
Message string `json:"message,omitempty"` …
```
=> *: refactor error stats

api/types/metric.go, metrics/request.go, metrics/request_test.go, request/schedule.go
* Show Code/Message so that it's easy to generate database schema
* Add URL in error
=> *: update ResponseError type

contrib/internal/utils/utils.go
If runner-group server is not found, let's return error instead of retrying. Maybe server is still running, but data loss happens in ETCD side. It's impossible to get result in this case. Fast-return is that only we can do.
=> contrib: fast return if runner-group server is not found

Makefile, cmd/kperf/commands/utils/helper.go, cmd/kperf/commands/virtualcluster/nodepool.go, contrib/cmd/runkperf/commands/bench/root.go, contrib/cmd/runkperf/commands/warmup/command.go, docs/getting-started.md, docs/runkperf.md, manifests/runnergroup/server/templates/flowcontrol.yaml, manifests/virtualcluster/nodecontrollers/templates/flowcontrol.yaml
This pull request includes several changes to the `Makefile`, Go source files, and documentation, primarily focusing on adding new functionality, updating configurations, and improving documentation. The most important changes are grouped by theme below:
* Added a new `image-clean` target to remove Docker images.
* Updated the `clean` target to remove additional binaries specified by `CONTRIB_BINARIES`.
* Introduced the `ApplyPriorityLevelConfiguration` function in `cmd/kperf/commands/utils/helper.go` to apply Kubernetes PriorityLevelConfiguration using `kubectl`.
* Updated `cmd/kperf/commands/virtualcluster/nodepool.go` to call the new `ApplyPriorityLevelConfiguration` function.
* Added instructions for obtaining KubeConfig for Azure, AWS, and GCP in `docs/getting-started.md`.
* Updated …
=> Add GCP support

contrib/cmd/runkperf/commands/bench/utils.go
runkperf bench always set the total to the value of the cli arg "total". When this isn't specified, a default value of 1000 was used regardless of what was configured in the spec.
Fix it by using the CLI arg value only if it's non-zero.
=> fix runkperf ignoring reqs total from spec

contrib/cmd/runkperf/commands/bench/cilium_cr_list.go, contrib/cmd/runkperf/commands/bench/root.go, contrib/internal/manifests/loadprofile/cilium_cr_list.yaml, contrib/internal/utils/kubectl_cmd.go, contrib/internal/utils/utils.go, go.mod
Add cilium_cr_list benchmark that:
(1) creates a configurable number of Cilium custom resources (synthetic) (2) generates stale list requests
This will be used to configure apiserver priority and fairness to protect apiserver from expensive LIST requests from Cilium (OOMKills due to explosion in temporary allocations from JSON serialization).
=> Add benchmark for Cilium custom resource stale list

request/requester.go
just in case that that importer doesn't use client-go@0.31.x
=> request: use internal function to support watchlist

contrib/internal/mountns/ns_linux.go, contrib/internal/mountns/ns_other.go, contrib/utils/kubectl_cmd.go, contrib/utils/kubectl_cmd_linux.go, contrib/utils/kubectl_cmd_other.go, contrib/utils/utils.go, contrib/utils/utils_linux.go, contrib/utils/utils_other.go
Just make it buildable on other platforms.
=> contrib: buildable on other platforms (darwin/wins)

go.mod, request/client.go, request/unstructuredscheme/serializer.go
When client receives watch event for CustomResources, we need to use unstructured to unmarshal event object. Otherwise, we run into the issue, like
```bash
Request stream failed: an error on the server ("unable to decode an event from
the watch stream: unable to decode watch event: no kind \"NodeNetworkConfig\"
is registered for version \"acn.azure.com/v1alpha\" in scheme
\"pkg/runtime/scheme.go:100\"") has prevented the request from succeeding
```
It's only used for watch list requests, since get/list responses will be discarded and there is no need to do serialization.
=> *: add unstructuredscheme pkg

cmd/kperf/commands/runnergroup/run.go, cmd/kperf/commands/runnergroup/server.go, manifests/runnergroup/server/templates/pod.yaml, manifests/runnergroup/server/values.yaml, runner/group/handler.go, runner/runnergroup_run.go, scripts/run_runner.sh
=> Allows to set verbosity on runner

virtualcluster/nodes_delete.go
This pull request modifies the `DeleteNodepool` function in `virtualcluster/nodes_delete.go` to improve error handling and cleanup logic when deleting virtual nodes and their controllers.
Improvements to error handling and cleanup:
* The deletion of virtual nodes (`cfg.nodeHelmReleaseName()`) now occurs before the deletion of the virtual node controller. This ensures proper cleanup order.
* Added error handling for the virtual node deletion step to check for `driver.ErrReleaseNotFound` and return a descriptive error if cleanup fails.
* Removed the redundant final call to delete the virtual node release, as it is now handled earlier in the function. The function now returns `nil` if all cleanup steps succeed.
=> delete virtual nodes before node controller

api/types/load_traffic.go, cmd/kperf/commands/runner/runner.go, contrib/cmd/runkperf/commands/bench/list_configmaps.go, contrib/cmd/runkperf/commands/bench/root.go, contrib/cmd/runkperf/commands/bench/utils.go, contrib/internal/manifests/loadprofile/list_configmaps.yaml, contrib/utils/utils.go, request/random.go, request/schedule.go
Add a new runkperf bench for listing configmaps:
1. Add total-time parameter to specify the duration for the runner execution;
2. Add list_configmaps benchmark command to execute benchmarks on specified resources
=> Add a new runkperf bench for listing configmaps

manifests/virtualcluster/nodecontrollers/templates/statefulsets.tpl
This pull request includes a small adjustment to resource requests in the `statefulsets.tpl` file. The change reduces the CPU request from `"200m"` to `"10m"` for improved resource allocation efficiency.
k top pod -n virtualnodes-kperf-io
example-4568   1m           17Mi            
example-4569   1m           13Mi            
example-457    1m           15Mi            
example-4570   1m           14Mi            
example-4571   1m           15Mi            
example-4572   1m           14Mi            
example-4573   1m           13Mi            
example-4574   1m           14Mi            
example-4575   1m           14Mi
=> lower kwok controller cpu requests to 10m

virtualcluster/nodes_common.go, virtualcluster/nodes_list.go
Since the lifecycle CRD and definition have been installed in **virtualnodeReleaseNamespace** namespace, it will show up when listing node pools. 
```shell
NAME            NODES       CPU     MEMORY (GiB)   MAX PODS   STATUS
lifecycle-crd   ? / <nil>   <nil>   <nil>          <nil>      deployed
lifecycle-def   ? / <nil>   <nil>   <nil>          <nil>      deployed
``` 
These should be ignored, as they are not actual virtual node pools.
=> cmd/kperf/virtualcluster: hide lifecycle CRD and definition when listing node pools

contrib/cmd/runkperf/commands/warmup/command.go
Update core warm-up threshold usage with example for forcing warm-up
=> "runkperf/warmup: Update core warm-up threshold usage with example for forcing warm-up

contrib/cmd/runkperf/commands/warmup/command.go
Log API server core readiness status and the core-warmup-ready-threshold before warm-up
=> runkperf/warmup:  Log API server core readiness status before warm-up

runner/runnergroup_delete.go
Remove the runnerGroupReleaseNamespace namespace, which has been created by Helm.
=> Clean up runner group namespace after deletion

contrib/cmd/runkperf/commands/bench/node100_pod10k.go, contrib/utils/utils.go
Extracted rollingUpdateFn() from DeployAndRepeatRollingUpdateDeployments() to enable future support for batching deployments and customizing the number of deployments to roll out.
=> Refactor: extract rollingUpdateFn for batching and customization

contrib/utils/kubectl_cmd.go
Make DeleteNamespace idempotent by adding --ignore-not-found=true flag. This prevents errors when deleting non-existent namespaces, like this:
> I0806 15:29:35.767611 1167408 klogger.go:28] "" level="info" msg="stop creating job"
I0806 15:29:35.767642 1167408 klogger.go:28] "" level="info" msg="cleanup namespace" name="job1pod100"
I0806 15:29:35.767703 1167408 klogger.go:28] "" level="info" msg="start command" cmd="/usr/local/bin/kubectl --kubeconfig /home/zhilan/aks-rp2/kubeconfig_kperf.yaml delete namespace job1pod100"
I0806 15:29:41.596080 1167408 klogger.go:28] "" level="info" msg="start command" cmd="/usr/local/bin/kperf vc nodepool --kubeconfig=/home/zhilan/aks-rp2/kubeconfig_kperf.yaml delete node10job1pod100"
runkperf: failed to delete existing runner group: failed to invoke …
=> Add --ignore-not-found flag to namespace deletion

contrib/cmd/runkperf/commands/bench/list_configmaps.go, contrib/utils/utils.go
Allow customizing ConfigMap naming pattern instead of using fixed "runkperf-bench" default. Falls back to default if empty string provided.
=> Add namePattern parameter to CreateConfigmaps func

manifests/runnergroup/server/templates/spec.yaml, runner/runnergroup_run.go
When invoking helm.StringPathValuesApplier during a PATCH operation, passing runnerGroupSpec as a raw string fails if the body contains special characters "[" or "]", like this:
```
- patch:
version: v1
resource: pods
namespace: kperf
patchType: json
name: test-pod4
body: |
[
{
"op": "replace",
"path": "/metadata/labels",
"value": {}
}
]
shares: 100
```
To resolve this:
- runnerGroupSpec is now base64-encoded before being passed to Helm
- Decoded in the Helm template using `b64dec` before applying `toYaml`
=> fix: base64-encode runnerGroupSpec to prevent errors in helm.StringPathValuesApplier
